### ISSUE TITLE
GameCenter_SavedGames_GetData() not working

### ISSUE THREAD

**Issue by 5krad** [YoYoGames/GMEXT-GameCenter#6]
Hello! 

GameCenter_SavedGames_GetData() doesn't seem to work.
In the async-social event / async event type "GameCenter_SavedGames_GetData", I wrote something like this:

	case "GameCenter_SavedGames_GetData":
		if (async_load[?"success"])
                    { 
                       //do something
                       show_debug_message("success")
                    }
		else
                   {
                      //do something else
                      show_debug_message("!success")
                  }
		break;

This  doesn't print any debug message. 
Am I using it wrong? Or could it be an extension bug? 
Can I get some advice on this?

I downloaded the extension from the marketplace. (GMS2.3 - Version 1.2.0. Published October 2, 2023)
I would appreciate it if you could check it out. 

IDE v2023.11.1.129
Runtime v2023.11.1.160

**Comment by jzavala-YYG** [comment]
Using the demo included in the marketplace I can see how **_GameCenter_SavedGames_GetData_** it's triggered correctly.
If problems persists open this ticket again please
