### ISSUE TITLE
Compile bug

### ISSUE THREAD

**Issue by ZigZaggh** [YoYoGames/GMEXT-GameCenter#7]
Hi

I get the following error in Xcode if I try to compile for iOS with the Game center extension V1.2.1 in an else empty project exported from windows.
`Unknown type name 'BN_ULONG'`

Any solution to this?

**Comment by DiasFranciscoA** [comment]
To assist you effectively, we require additional details or a sample project that demonstrates the problem you're encountering.

* Could you please specify the version of the IDE and runtime environment you are utilizing?
* What is the current version of XCode installed on your system?
* Additionally, have you reviewed the instructions in the [Setup](https://github.com/YoYoGames/GMEXT-GameCenter/wiki/setup) section of our wiki? This might contain relevant information that could help resolve your issue.

Your cooperation in providing these details would be greatly appreciated, as it will enable us to better understand and address your concern.
